// components/PageCta.tsx
import Link from 'next/link';

interface PageCtaProps {
    title?: string;
    text?: string;
    primaryLabel?: string;
    primaryLink?: string;
    secondaryLabel?: string;
    secondaryLink?: string;
}

export default function PageCta({
    title = 'Ninguém constrói pontes sozinho',
    text = 'Sua doação, seu tempo ou sua articulação local sustentam a acolhida de quem chega. Some-se à rede do SPM.',
    primaryLabel = 'Como Ajudar',
    primaryLink = '/como-ajudar',
    secondaryLabel = 'Fale Conosco',
    secondaryLink = '/fale-conosco',
}: PageCtaProps) {
    return (
        <section className="cta-band">
            <div className="container">
                <h2>{title}</h2>
                <p>{text}</p>
                <div className="cta-band__actions">
                    <Link className="btn btn--cta" href={primaryLink}>
                        <i className="fas fa-heart"></i> {primaryLabel}
                    </Link>
                    <Link className="btn btn--light" href={secondaryLink}>
                        {secondaryLabel}
                    </Link>
                </div>
            </div>
        </section>
    );
}

// src/app/shared/components/page-cta/page-cta.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';

@Component({
    selector: 'app-page-cta',
    standalone: true,
    imports: [CommonModule, RouterLink],
    template: `
        <section class="cta-band">
            <div class="container">
                <h2>{{ title }}</h2>
                <p>{{ text }}</p>
                <div class="cta-band__actions">
                    <a class="btn btn--cta" [routerLink]="primaryLink">
                        <i class="fas fa-heart"></i> {{ primaryLabel }}
                    </a>
                    <a class="btn btn--light" [routerLink]="secondaryLink">{{ secondaryLabel }}</a>
                </div>
            </div>
        </section>
    `,
})
export class PageCtaComponent {
    @Input() title = 'Ninguém constrói pontes sozinho';
    @Input() text =
        'Sua doação, seu tempo ou sua articulação local sustentam a acolhida de quem chega. Some-se à rede do SPM.';
    @Input() primaryLabel = 'Como Ajudar';
    @Input() primaryLink = '/como-ajudar';
    @Input() secondaryLabel = 'Fale Conosco';
    @Input() secondaryLink = '/fale-conosco';
}
